# name: Add Reviewer for Freezed Branches

# on:
#   pull_request:
#     branches:
#       - 'v*.*' # Matches branches like v1.10, v1.11, etc.

# jobs:
#   add-reviewer:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Add KomissarMaria as a reviewer
#         env:
#           GITHUB_TOKEN: ${{ secrets.TOKEN }}
#         run: |
#           pr_number=${{ github.event.pull_request.number }}
#           repo=${{ github.repository }}
#           curl -s -X POST \
#             -H "Accept: application/vnd.github+json" \
#             -H "Authorization: Bearer $GITHUB_TOKEN" \
#             https://api.github.com/repos/$repo/pulls/$pr_number/requested_reviewers \
#             -d '{"reviewers":["KomissarMaria"]}'
