name: Add Reviewer for Freezed Branches

on:
  pull_request:
    branches:
      - 'v*.*' # Targets branches with names like v1.10, v1.11, etc.

jobs:
  add-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Add Reviewer
        uses: octokit/request-action@v2
        with:
          route: POST /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers
          reviewers: KomisarMariia
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
